version: '{build}'
branches:
  only:
  - master
configuration: Release
init:
- ps: Update-AppveyorBuild -Version "1.$(Get-Date -format yyyy.M).$env:appveyor_build_number"
assembly_info:
  patch: true
  file: '**\VersionInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
build:
  verbosity: minimal
after_build:
- 7z a Cinteros.XrmToolBox.Plugins_%APPVEYOR_BUILD_VERSION%.zip %APPVEYOR_BUILD_FOLDER%\Output\%CONFIGURATION%\Cinteros.Xrm.*.dll
- appveyor PushArtifact Cinteros.XrmToolBox.Plugins_%APPVEYOR_BUILD_VERSION%.zip
deploy:
- provider: Environment
  name: GitHubCintXTB
- provider: FTP
  host: rappen.net
  protocol: ftp
  username: Jonas
  password:
    secure: tlAywufGDNedgIwqqBUmsA==
  folder: rappen/Cinteros
