version: '{branch}.{build}'
skip_tags: true
configuration: Release
platform: Any CPU
shallow_clone: true
init:
- SET /A "year=%Date:~10,4%"
- SET /A "month=%Date:~4,2%"
- SET /A "day=%Date:~7,2%"
assembly_info:
  patch: true
  file: VersionInfo.cs
  assembly_version: 1.$(year).$(month).$(day)
  assembly_file_version: 1.$(year).$(month).$(day)
  assembly_informational_version: $(APPVEYOR_REPO_COMMIT)
build:
  project: XrmToolBox.Plugins.sln
  parallel: true
  verbosity: normal
after_build:
- 7z a XrmToolBox.Plugins-%APPVEYOR_REPO_COMMIT:~0,7%.zip %APPVEYOR_BUILD_FOLDER%\Output\%CONFIGURATION%\Cinteros.Xrm.*.dll
- appveyor PushArtifact XrmToolBox.Plugins-%APPVEYOR_REPO_COMMIT:~0,7%.zip
deploy:
- provider: GitHub
  tag: 1.$(year).$(month).$(day)
  auth_token:
    secure: U8WF6FtOs2fsQe/2F8k5LNlWNkLlMiACIZvgj1EN9AuYP2cX3y3t5agU0nKs6X2sv5wVnDrgtEqlBTlB5/StWImhuCFPpwNnRVwFVQjR8OM=
  prerelease: true